# Generated by Django 4.1.3 on 2022-11-13 02:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Construidas por', max_length=80)),
            ],
            options={
                'verbose_name': 'Contruido por',
                'verbose_name_plural': 'Contruido por',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de muerte', max_length=80)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='StateInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Estado de la infraestructura vial', max_length=80)),
            ],
            options={
                'verbose_name': 'Estado de infraestructura',
                'verbose_name_plural': 'Estados de infraestructuras',
            },
        ),
        migrations.CreateModel(
            name='TypeDomesticViolence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de violencia', max_length=80)),
            ],
            options={
                'verbose_name': 'Tipo de violencia domestica',
                'verbose_name_plural': 'Tipos de violencia domestica',
            },
        ),
        migrations.CreateModel(
            name='TypeInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de la infraestrutura vial', max_length=80)),
            ],
            options={
                'verbose_name': 'Tipo de infraestructura',
                'verbose_name_plural': 'Tipos de infraestructuras',
            },
        ),
        migrations.CreateModel(
            name='TypeViolentDeaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de muerte', max_length=80)),
            ],
            options={
                'verbose_name': 'Tipo de muerte violenta',
                'verbose_name_plural': 'Tipo de muerte violentas',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de vehiculo', max_length=80)),
            ],
            options={
                'verbose_name': 'Tipo de vehiculo',
                'verbose_name_plural': 'Tipos de vehiculos',
            },
        ),
        migrations.CreateModel(
            name='ViolentDeaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeviolentdeaths')),
            ],
            options={
                'verbose_name': 'Muerte violenta',
                'verbose_name_plural': 'Muertes violentas',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('plate', models.CharField(help_text='Placa del vehiculo', max_length=7)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='LivingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('stratum', models.IntegerField()),
                ('builtby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.builtby')),
            ],
            options={
                'verbose_name': 'Residencia',
                'verbose_name_plural': 'Residencias',
            },
        ),
        migrations.CreateModel(
            name='InfrastructureRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stateinfrastructure')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeinfrastructure')),
            ],
            options={
                'verbose_name': 'Infraestructura vial',
                'verbose_name_plural': 'Infraestructuras viales',
            },
        ),
        migrations.CreateModel(
            name='DomesticViolence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gender')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typedomesticviolence')),
            ],
            options={
                'verbose_name': 'Violencia domestica',
                'verbose_name_plural': 'Violencia domestica',
            },
        ),
    ]
