# Generated by Django 4.1 on 2022-10-30 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolentDeaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('type', models.CharField(choices=[('suicidio', 'Suicidio'), ('muerte_accidental', 'Muerte acciental'), ('muerte_accidente_transporte', 'Muerte accidental de transporte'), ('homicidio', 'Homicidio')], help_text='Tipo de muerte', max_length=80)),
            ],
        ),
    ]
