# Generated by Django 4.1 on 2022-10-30 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeViolentDeaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de muerte', max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='violentdeaths',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeviolentdeaths'),
        ),
    ]
