# Generated by Django 4.1 on 2022-10-31 04:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_typeviolentdeaths_alter_violentdeaths_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de muerte', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDomesticViolence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de violencia', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='DomesticViolence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gender')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typedomesticviolence')),
            ],
        ),
    ]
