# Generated by Django 4.1 on 2022-11-01 04:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gender_typedomesticviolence_domesticviolence'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Construidas por', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='LivingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('stratum', models.IntegerField()),
                ('builtby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.builtby')),
            ],
        ),
    ]
