# Generated by Django 4.1 on 2022-11-01 05:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_builtby_livingplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Estado de la infraestructura vial', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de la infraestrutura vial', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de vehiculo', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('plate', models.CharField(help_text='Placa del vehiculo', max_length=6)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stateinfrastructure')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeinfrastructure')),
            ],
        ),
    ]
