# Generated by Django 4.1.3 on 2022-11-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_stateinfrastructure_typeinfrastructure_vehicletype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builtby',
            options={'verbose_name': 'Contruido por', 'verbose_name_plural': 'Contruido por'},
        ),
        migrations.AlterModelOptions(
            name='domesticviolence',
            options={'verbose_name': 'Violencia domestica', 'verbose_name_plural': 'Violencia domestica'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='infrastructureroad',
            options={'verbose_name': 'Infraestructura vial', 'verbose_name_plural': 'Infraestructuras viales'},
        ),
        migrations.AlterModelOptions(
            name='livingplace',
            options={'verbose_name': 'Residencia', 'verbose_name_plural': 'Residencias'},
        ),
        migrations.AlterModelOptions(
            name='stateinfrastructure',
            options={'verbose_name': 'Estado de infraestructura', 'verbose_name_plural': 'Estados de infraestructuras'},
        ),
        migrations.AlterModelOptions(
            name='typedomesticviolence',
            options={'verbose_name': 'Tipo de violencia domestica', 'verbose_name_plural': 'Tipos de violencia domestica'},
        ),
        migrations.AlterModelOptions(
            name='typeinfrastructure',
            options={'verbose_name': 'Tipo de infraestructura', 'verbose_name_plural': 'Tipos de infraestructuras'},
        ),
        migrations.AlterModelOptions(
            name='typeviolentdeaths',
            options={'verbose_name': 'Tipo de muerte violenta', 'verbose_name_plural': 'Tipo de muerte violentas'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehiculo', 'verbose_name_plural': 'Vehiculos'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'Tipo de vehiculo', 'verbose_name_plural': 'Tipos de vehiculos'},
        ),
        migrations.AlterModelOptions(
            name='violentdeaths',
            options={'verbose_name': 'Muerte violenta', 'verbose_name_plural': 'Muertes violentas'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(help_text='Placa del vehiculo', max_length=7),
        ),
    ]
